### ISSUE TITLE
Graph does not show up

### ISSUE THREAD

**Issue by studiawan** [totetmatt/GephiStreamer#2]
I am running the example code and it is successfully created nodes (only in Data Laboratory panel) but the script can not create the edge. In the Overview panel, I can not see the graph as shown in your example GIF image. 
![datalab](https://cloud.githubusercontent.com/assets/1132921/12486641/1d304264-c096-11e5-82cf-1b8cae7b0a16.png)

Do you have any idea what happens here?

**Comment by totetmatt** [comment]
My bad, I forgot to add the `stream.add_edge(edge_ab)` after the edge creation. See the latest version of the example, should works now.

**Comment by studiawan** [comment]
It is working now, thank you!
